"""
Script para popular a tabela Player com dados de jogadores de futebol
Execute este script após inicializar o banco de dados
"""
import sys
import os

# Adiciona o diretório raiz do projeto ao path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app import create_app
from extensions import db
from models.Player import Player


def seed_players():
    """
    Popula a tabela Player com dados de jogadores famosos
    """
    app = create_app()
    
    with app.app_context():
        # Verifica se já existem jogadores no banco
        existing_players = Player.query.count()
        if existing_players > 0:
            print(f"⚠️  Já existem {existing_players} jogadores no banco. Deseja continuar?")
            print("   (O script irá adicionar novos jogadores se não existirem)")
        
        # Lista de jogadores para inserir
        players_data = [
            # Jogadores existentes (mantidos)
            {
                'name': 'NEYMAR JR',
                'playedAt': 'Santos,Barcelona,PSG,Al-Hilal',
                'managedBy': 'Tite,Dunga',
                'playedWith': 'MESSI,SUAREZ,INIESTA',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa Libertadores,Champions League,Copa do Brasil',
                'leaguesPlayed': 'Brasileirão,La Liga,Ligue 1',
                'position': 'Atacante',
                'goals': 400,
                'totalGames': 650,
                'assists': 250,
                'totalTrophies': 25,
                'redCards': 8,
            },
            {
                'name': 'MESSI',
                'playedAt': 'Barcelona,PSG,Inter Miami',
                'managedBy': 'Pep Guardiola,Luis Enrique',
                'playedWith': 'NEYMAR JR,SUAREZ,XAVI,INIESTA',
                'nationality': 'Argentina',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga,Ballon dOr',
                'leaguesPlayed': 'La Liga,Ligue 1,MLS',
                'position': 'Atacante',
                'goals': 800,
                'totalGames': 1000,
                'assists': 350,
                'totalTrophies': 45,
                'redCards': 3,
            },
            {
                'name': 'RONALDO',
                'playedAt': 'Manchester United,Real Madrid,Juventus,Al Nassr',
                'managedBy': 'Sir Alex Ferguson,Zidane',
                'playedWith': 'BENZEMA,MODRIC,BALE',
                'nationality': 'Portugal',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga,Ballon dOr',
                'leaguesPlayed': 'Premier League,La Liga,Serie A',
                'position': 'Atacante',
                'goals': 850,
                'totalGames': 1200,
                'assists': 250,
                'totalTrophies': 35,
                'redCards': 11,
            },
            {
                'name': 'MBAPPE',
                'playedAt': 'Monaco,PSG,Real Madrid',
                'managedBy': 'Didier Deschamps,Thomas Tuchel',
                'playedWith': 'NEYMAR JR,MESSI,RAMOS',
                'nationality': 'França',
                'trophiesEarned': 'Copa do Mundo,Ligue 1',
                'leaguesPlayed': 'Ligue 1,La Liga',
                'position': 'Atacante',
                'goals': 300,
                'totalGames': 350,
                'assists': 120,
                'totalTrophies': 15,
                'redCards': 2,
            },
            {
                'name': 'HAALAND',
                'playedAt': 'Molde,RB Salzburg,Borussia Dortmund,Manchester City',
                'managedBy': 'Pep Guardiola,Erling Haaland Sr',
                'playedWith': 'DE BRUYNE,FODEN',
                'nationality': 'Noruega',
                'trophiesEarned': 'Champions League,Premier League,Bundesliga',
                'leaguesPlayed': 'Premier League,Bundesliga',
                'position': 'Atacante',
                'goals': 250,
                'totalGames': 250,
                'assists': 50,
                'totalTrophies': 8,
                'redCards': 1,
            },
            {
                'name': 'VINI JR',
                'playedAt': 'Flamengo,Real Madrid',
                'managedBy': 'Carlo Ancelotti',
                'playedWith': 'BENZEMA,MODRIC,RODRYGO,BELLINGHAM',
                'nationality': 'Brasil',
                'trophiesEarned': 'Champions League,La Liga,Copa do Brasil',
                'leaguesPlayed': 'Brasileirão,La Liga',
                'position': 'Atacante',
                'goals': 150,
                'totalGames': 300,
                'assists': 100,
                'totalTrophies': 12,
                'redCards': 5,
            },
            {
                'name': 'KANE',
                'playedAt': 'Tottenham,Bayern Munich',
                'managedBy': 'Mauricio Pochettino,Thomas Tuchel',
                'playedWith': 'SON,LEWANDOWSKI',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Bundesliga',
                'leaguesPlayed': 'Premier League,Bundesliga',
                'position': 'Atacante',
                'goals': 400,
                'totalGames': 600,
                'assists': 100,
                'totalTrophies': 2,
                'redCards': 0,
            },
            {
                'name': 'M. SALAH',
                'playedAt': 'Basel,Chelsea,Roma,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'MANE,VAN DIJK',
                'nationality': 'Egito',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League,Serie A',
                'position': 'Atacante',
                'goals': 350,
                'totalGames': 550,
                'assists': 150,
                'totalTrophies': 10,
                'redCards': 1,
            },
            {
                'name': 'BENZEMA',
                'playedAt': 'Lyon,Real Madrid,Al Ittihad',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'RONALDO,MODRIC,BALE',
                'nationality': 'França',
                'trophiesEarned': 'Champions League,La Liga,Ballon dOr',
                'leaguesPlayed': 'La Liga,Ligue 1',
                'position': 'Atacante',
                'goals': 450,
                'totalGames': 750,
                'assists': 200,
                'totalTrophies': 30,
                'redCards': 6,
            },
            {
                'name': 'MODRIC',
                'playedAt': 'Dinamo Zagreb,Tottenham,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'RONALDO,BENZEMA,KROOS',
                'nationality': 'Croácia',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga,Ballon dOr',
                'leaguesPlayed': 'Premier League,La Liga',
                'position': 'Meio-campo',
                'goals': 100,
                'totalGames': 800,
                'assists': 150,
                'totalTrophies': 25,
                'redCards': 3,
            },
            {
                'name': 'RODRYGO',
                'playedAt': 'Santos,Real Madrid',
                'managedBy': 'Carlo Ancelotti',
                'playedWith': 'VINI JR,BENZEMA,MODRIC,BELLINGHAM',
                'nationality': 'Brasil',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Brasileirão,La Liga',
                'position': 'Atacante',
                'goals': 80,
            },
            {
                'name': 'BELLINGHAM',
                'playedAt': 'Birmingham,Borussia Dortmund,Real Madrid',
                'managedBy': 'Carlo Ancelotti',
                'playedWith': 'VINI JR,MODRIC,KROOS',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Premier League,Bundesliga,La Liga',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'DE BRUYNE',
                'playedAt': 'Genk,Werder Bremen,Chelsea,Wolfsburg,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'HAALAND,FODEN',
                'nationality': 'Bélgica',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League,Bundesliga',
                'position': 'Meio-campo',
                'goals': 150,
            },
            {
                'name': 'LEWANDOWSKI',
                'playedAt': 'Lech Poznan,Borussia Dortmund,Bayern Munich,Barcelona',
                'managedBy': 'Pep Guardiola,Hansi Flick',
                'playedWith': 'Muller,Neuer,Goretzka,Kane',
                'nationality': 'Polônia',
                'trophiesEarned': 'Champions League,Bundesliga,La Liga',
                'leaguesPlayed': 'Bundesliga,La Liga',
                'position': 'Atacante',
                'goals': 600,
            },
            {
                'name': 'SUAREZ',
                'playedAt': 'Nacional,Groningen,Ajax,Liverpool,Barcelona,Atletico Madrid',
                'managedBy': 'Luis Enrique,Diego Simeone',
                'playedWith': 'MESSI,NEYMAR JR,INIESTA,GRIEZMANN',
                'nationality': 'Uruguai',
                'trophiesEarned': 'Champions League,La Liga,Premier League',
                'leaguesPlayed': 'Premier League,La Liga,Eredivisie',
                'position': 'Atacante',
                'goals': 500
            },
            {
                'name': 'INIESTA',
                'playedAt': 'Barcelona,Vissel Kobe',
                'managedBy': 'Pep Guardiola,Luis Enrique',
                'playedWith': 'MESSI,XAVI',
                'nationality': 'Espanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga',
                'leaguesPlayed': 'La Liga,J-League',
                'position': 'Meio-campo',
                'goals': 100,
            },
            {
                'name': 'XAVI',
                'playedAt': 'Barcelona,Al Sadd',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'MESSI,INIESTA',
                'nationality': 'Espanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga',
                'leaguesPlayed': 'La Liga',
                'position': 'Meio-campo',
                'goals': 80,
            },
            {
                'name': 'RAMOS',
                'playedAt': 'Sevilla,Real Madrid,PSG',
                'managedBy': 'Zidane,Carlo Ancelotti',
                'playedWith': 'RONALDO,BENZEMA,MODRIC,MBAPPE',
                'nationality': 'Espanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga',
                'leaguesPlayed': 'La Liga,Ligue 1',
                'position': 'Zagueiro',
                'goals': 100,
            },
            {
                'name': 'BALE',
                'playedAt': 'Southampton,Tottenham,Real Madrid,LA Galaxy',
                'managedBy': 'Zidane,Carlo Ancelotti',
                'playedWith': 'RONALDO,BENZEMA,MODRIC',
                'nationality': 'País de Gales',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Premier League,La Liga,MLS',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'KROOS',
                'playedAt': 'Bayern Munich,Bayer Leverkusen,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'MODRIC,BENZEMA,RONALDO',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga',
                'leaguesPlayed': 'Bundesliga,La Liga',
                'position': 'Meio-campo',
                'goals': 80,
            },
            {
                'name': 'SON',
                'playedAt': 'Hamburger SV,Bayer Leverkusen,Tottenham',
                'managedBy': 'Mauricio Pochettino',
                'playedWith': 'KANE',
                'nationality': 'Coreia do Sul',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Premier League,Bundesliga',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'MANE',
                'playedAt': 'Metz,Salzburg,Southampton,Liverpool,Bayern Munich,Al Nassr',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,VAN DIJK',
                'nationality': 'Senegal',
                'trophiesEarned': 'Champions League,Premier League,Bundesliga',
                'leaguesPlayed': 'Premier League,Bundesliga',
                'position': 'Atacante',
                'goals': 250,
            },
            {
                'name': 'VAN DIJK',
                'playedAt': 'Groningen,Celtic,Southampton,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,MANE',
                'nationality': 'Holanda',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League,Scottish Premiership',
                'position': 'Zagueiro',
                'goals': 50,
            },
            {
                'name': 'FODEN',
                'playedAt': 'Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'DE BRUYNE,HAALAND',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Meio-campo',
                'goals': 100,
            },
            {
                'name': 'GRIEZMANN',
                'playedAt': 'Real Sociedad,Atletico Madrid,Barcelona,Atletico Madrid',
                'managedBy': 'Diego Simeone,Luis Enrique',
                'playedWith': 'SUAREZ',
                'nationality': 'França',
                'trophiesEarned': 'Copa do Mundo,La Liga',
                'leaguesPlayed': 'La Liga',
                'position': 'Atacante',
                'goals': 300,
            },
            {
                'name': 'COURTOIS',
                'playedAt': 'Genk,Atletico Madrid,Chelsea,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'RAMOS,MODRIC,BENZEMA',
                'nationality': 'Bélgica',
                'trophiesEarned': 'Champions League,La Liga,Premier League',
                'leaguesPlayed': 'La Liga,Premier League',
                'position': 'Goleiro',
                'goals': 0,
            },
            {
                'name': 'PEDRI',
                'playedAt': 'Las Palmas,Barcelona',
                'managedBy': 'Xavi',
                'playedWith': 'MESSI',
                'nationality': 'Espanha',
                'trophiesEarned': 'La Liga',
                'leaguesPlayed': 'La Liga',
                'position': 'Meio-campo',
                'goals': 30,
            },
            {
                'name': 'BRUNO FERNANDES',
                'playedAt': 'Novara,Udinese,Sampdoria,Sporting CP,Manchester United',
                'managedBy': 'Ole Gunnar Solskjaer,Erik ten Hag',
                'playedWith': 'RASHFORD,CAVANI',
                'nationality': 'Portugal',
                'trophiesEarned': 'Europa League,EFL Cup',
                'leaguesPlayed': 'Serie A,Primeira Liga,Premier League',
                'position': 'Meio-campo',
                'goals': 150,
            },
            {
                'name': 'RASHFORD',
                'playedAt': 'Manchester United',
                'managedBy': 'Ole Gunnar Solskjaer,Erik ten Hag',
                'playedWith': 'BRUNO FERNANDES,CAVANI',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Europa League,EFL Cup',
                'leaguesPlayed': 'Premier League',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'ALISSON',
                'playedAt': 'Internacional,Roma,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,MANE,VAN DIJK',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa do Mundo,Champions League,Premier League',
                'leaguesPlayed': 'Brasileirão,Serie A,Premier League',
                'position': 'Goleiro',
                'goals': 0,
            },
            {
                'name': 'EDERSON',
                'playedAt': 'Benfica,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'DE BRUYNE,HAALAND,FODEN',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa América,Champions League,Premier League',
                'leaguesPlayed': 'Primeira Liga,Premier League',
                'position': 'Goleiro',
                'goals': 0,
            },
            {
                'name': 'CASEMIRO',
                'playedAt': 'Sao Paulo,Porto,Real Madrid,Manchester United',
                'managedBy': 'Carlo Ancelotti,Zidane,Erik ten Hag',
                'playedWith': 'MODRIC,KROOS,BENZEMA',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa América,Champions League,La Liga',
                'leaguesPlayed': 'Brasileirão,Primeira Liga,La Liga,Premier League',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'MARQUINHOS',
                'playedAt': 'Corinthians,Roma,PSG',
                'managedBy': 'Thomas Tuchel,Unai Emery',
                'playedWith': 'NEYMAR JR,MBAPPE,VERRATTI',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa América,Ligue 1',
                'leaguesPlayed': 'Brasileirão,Serie A,Ligue 1',
                'position': 'Zagueiro',
                'goals': 30,
            },
            {
                'name': 'THIAGO SILVA',
                'playedAt': 'Fluminense,AC Milan,PSG,Chelsea',
                'managedBy': 'Thomas Tuchel,Carlo Ancelotti',
                'playedWith': 'IBRAHIMOVIC,NEYMAR JR',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa América,Champions League,Ligue 1',
                'leaguesPlayed': 'Brasileirão,Serie A,Ligue 1,Premier League',
                'position': 'Zagueiro',
                'goals': 20,
            },
            {
                'name': 'FABINHO',
                'playedAt': 'Fluminense,Monaco,Liverpool,Al Ittihad',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,MANE,ALISSON',
                'nationality': 'Brasil',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Brasileirão,Ligue 1,Premier League',
                'position': 'Meio-campo',
                'goals': 30,
            },
            {
                'name': 'GABRIEL JESUS',
                'playedAt': 'Palmeiras,Manchester City,Arsenal',
                'managedBy': 'Pep Guardiola,Mikel Arteta',
                'playedWith': 'DE BRUYNE,HAALAND',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa América,Premier League',
                'leaguesPlayed': 'Brasileirão,Premier League',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'RICHARLISON',
                'playedAt': 'America MG,Fluminense,Watford,Everton,Tottenham',
                'managedBy': 'Mauricio Pochettino',
                'playedWith': 'SON,KANE',
                'nationality': 'Brasil',
                'trophiesEarned': 'Copa América',
                'leaguesPlayed': 'Brasileirão,Premier League',
                'position': 'Atacante',
                'goals': 150,
            },
            {
                'name': 'ANTONY',
                'playedAt': 'Sao Paulo,Ajax,Manchester United',
                'managedBy': 'Erik ten Hag',
                'playedWith': 'RASHFORD,BRUNO FERNANDES',
                'nationality': 'Brasil',
                'trophiesEarned': 'Eredivisie',
                'leaguesPlayed': 'Brasileirão,Eredivisie,Premier League',
                'position': 'Atacante',
                'goals': 80,
            },
            {
                'name': 'MARTINELLI',
                'playedAt': 'Ituano,Arsenal',
                'managedBy': 'Mikel Arteta',
                'playedWith': 'GABRIEL JESUS,SAKA',
                'nationality': 'Brasil',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Brasileirão,Premier League',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'SAKA',
                'playedAt': 'Arsenal',
                'managedBy': 'Mikel Arteta',
                'playedWith': 'GABRIEL JESUS,MARTINELLI',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'OBLAK',
                'playedAt': 'Benfica,Atletico Madrid',
                'managedBy': 'Diego Simeone',
                'playedWith': 'GRIEZMANN,SUAREZ',
                'nationality': 'Eslovênia',
                'trophiesEarned': 'La Liga,Europa League',
                'leaguesPlayed': 'Primeira Liga,La Liga',
                'position': 'Goleiro',
                'goals': 0,
            },
            {
                'name': 'VARANE',
                'playedAt': 'Lens,Real Madrid,Manchester United',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'RAMOS,MODRIC,BENZEMA',
                'nationality': 'França',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga',
                'leaguesPlayed': 'Ligue 1,La Liga,Premier League',
                'position': 'Zagueiro',
                'goals': 10,
            },
            {
                'name': 'CARVAJAL',
                'playedAt': 'Real Madrid Castilla,Bayer Leverkusen,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'MODRIC,BENZEMA,RAMOS',
                'nationality': 'Espanha',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Bundesliga,La Liga',
                'position': 'Lateral',
                'goals': 10,
            },
            {
                'name': 'MENDY',
                'playedAt': 'Le Havre,Marseille,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'BENZEMA,MODRIC',
                'nationality': 'França',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Ligue 1,La Liga',
                'position': 'Lateral',
                'goals': 5,
            },
            {
                'name': 'MILITAO',
                'playedAt': 'Sao Paulo,Porto,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'BENZEMA,MODRIC,ALABA',
                'nationality': 'Brasil',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Brasileirão,Primeira Liga,La Liga',
                'position': 'Zagueiro',
                'goals': 10,
            },
            {
                'name': 'ALABA',
                'playedAt': 'Austria Vienna,Bayern Munich,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Pep Guardiola',
                'playedWith': 'LEWANDOWSKI,NEUER,BENZEMA',
                'nationality': 'Áustria',
                'trophiesEarned': 'Champions League,Bundesliga,La Liga',
                'leaguesPlayed': 'Bundesliga,La Liga',
                'position': 'Zagueiro',
                'goals': 30,
            },
            {
                'name': 'CAMAVINGA',
                'playedAt': 'Rennes,Real Madrid',
                'managedBy': 'Carlo Ancelotti',
                'playedWith': 'MODRIC,BENZEMA,BELLINGHAM',
                'nationality': 'França',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Ligue 1,La Liga',
                'position': 'Meio-campo',
                'goals': 20,
            },
            {
                'name': 'TCHOUAMENI',
                'playedAt': 'Bordeaux,Monaco,Real Madrid',
                'managedBy': 'Carlo Ancelotti',
                'playedWith': 'MODRIC,BENZEMA,BELLINGHAM',
                'nationality': 'França',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Ligue 1,La Liga',
                'position': 'Meio-campo',
                'goals': 10,
            },
            {
                'name': 'VALVERDE',
                'playedAt': 'Penarol,Real Madrid',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'MODRIC,BENZEMA,KROOS',
                'nationality': 'Uruguai',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'La Liga',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'GAVI',
                'playedAt': 'Barcelona',
                'managedBy': 'Xavi',
                'playedWith': 'PEDRI,LEWANDOWSKI',
                'nationality': 'Espanha',
                'trophiesEarned': 'La Liga',
                'leaguesPlayed': 'La Liga',
                'position': 'Meio-campo',
                'goals': 20,
            },
            {
                'name': 'DE JONG',
                'playedAt': 'Willem II,Ajax,Barcelona',
                'managedBy': 'Xavi,Ernesto Valverde',
                'playedWith': 'PEDRI,LEWANDOWSKI',
                'nationality': 'Holanda',
                'trophiesEarned': 'La Liga,Eredivisie',
                'leaguesPlayed': 'Eredivisie,La Liga',
                'position': 'Meio-campo',
                'goals': 30,
            },
            {
                'name': 'TER STEGEN',
                'playedAt': 'Borussia Monchengladbach,Barcelona',
                'managedBy': 'Xavi,Luis Enrique',
                'playedWith': 'MESSI,INIESTA,LEWANDOWSKI',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Bundesliga,La Liga',
                'position': 'Goleiro',
                'goals': 0,
            },
            {
                'name': 'ARAUJO',
                'playedAt': 'Boston River,Barcelona',
                'managedBy': 'Xavi',
                'playedWith': 'PEDRI,LEWANDOWSKI',
                'nationality': 'Uruguai',
                'trophiesEarned': 'La Liga',
                'leaguesPlayed': 'La Liga',
                'position': 'Zagueiro',
                'goals': 5,
            },
            {
                'name': 'KOUNDE',
                'playedAt': 'Bordeaux,Sevilla,Barcelona',
                'managedBy': 'Xavi',
                'playedWith': 'PEDRI,LEWANDOWSKI',
                'nationality': 'França',
                'trophiesEarned': 'La Liga',
                'leaguesPlayed': 'Ligue 1,La Liga',
                'position': 'Zagueiro',
                'goals': 5,
            },
            {
                'name': 'BALDE',
                'playedAt': 'Barcelona',
                'managedBy': 'Xavi',
                'playedWith': 'PEDRI,GAVI',
                'nationality': 'Espanha',
                'trophiesEarned': 'La Liga',
                'leaguesPlayed': 'La Liga',
                'position': 'Lateral',
                'goals': 5,
            },
            {
                'name': 'LEAO',
                'playedAt': 'Sporting CP,Lille,AC Milan',
                'managedBy': 'Stefano Pioli',
                'playedWith': 'GIRoud,IBRAHIMOVIC',
                'nationality': 'Portugal',
                'trophiesEarned': 'Serie A',
                'leaguesPlayed': 'Primeira Liga,Ligue 1,Serie A',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'OSIMHEN',
                'playedAt': 'Wolfsburg,Charleroi,Lille,Napoli',
                'managedBy': 'Luciano Spalletti',
                'playedWith': 'KVARATSKHELIA',
                'nationality': 'Nigéria',
                'trophiesEarned': 'Serie A',
                'leaguesPlayed': 'Bundesliga,Ligue 1,Serie A',
                'position': 'Atacante',
                'goals': 150,
            },
            {
                'name': 'KVARATSKHELIA',
                'playedAt': 'Dinamo Tbilisi,Rubin Kazan,Napoli',
                'managedBy': 'Luciano Spalletti',
                'playedWith': 'OSIMHEN',
                'nationality': 'Geórgia',
                'trophiesEarned': 'Serie A',
                'leaguesPlayed': 'Serie A',
                'position': 'Atacante',
                'goals': 50,
            },
            {
                'name': 'BARELLA',
                'playedAt': 'Cagliari,Inter Milan',
                'managedBy': 'Antonio Conte,Simone Inzaghi',
                'playedWith': 'LAUTARO,LUKAKU',
                'nationality': 'Itália',
                'trophiesEarned': 'Serie A,Europa League',
                'leaguesPlayed': 'Serie A',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'LAUTARO',
                'playedAt': 'Racing Club,Inter Milan',
                'managedBy': 'Antonio Conte,Simone Inzaghi',
                'playedWith': 'LUKAKU,BARELLA',
                'nationality': 'Argentina',
                'trophiesEarned': 'Copa do Mundo,Serie A',
                'leaguesPlayed': 'Serie A',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'LUKAKU',
                'playedAt': 'Anderlecht,Chelsea,Everton,Manchester United,Inter Milan,Chelsea,Roma',
                'managedBy': 'Antonio Conte,Jose Mourinho',
                'playedWith': 'LAUTARO,BARELLA',
                'nationality': 'Bélgica',
                'trophiesEarned': 'Serie A',
                'leaguesPlayed': 'Premier League,Serie A',
                'position': 'Atacante',
                'goals': 300,
            },
            {
                'name': 'DYBALA',
                'playedAt': 'Palermo,Juventus,Roma',
                'managedBy': 'Massimiliano Allegri,Jose Mourinho',
                'playedWith': 'RONALDO,CHIESA',
                'nationality': 'Argentina',
                'trophiesEarned': 'Serie A',
                'leaguesPlayed': 'Serie A',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'CHIESA',
                'playedAt': 'Fiorentina,Juventus',
                'managedBy': 'Massimiliano Allegri',
                'playedWith': 'RONALDO,DYBALA',
                'nationality': 'Itália',
                'trophiesEarned': 'Serie A',
                'leaguesPlayed': 'Serie A',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'VLAHOVIC',
                'playedAt': 'Fiorentina,Juventus',
                'managedBy': 'Massimiliano Allegri',
                'playedWith': 'CHIESA',
                'nationality': 'Sérvia',
                'trophiesEarned': 'Serie A',
                'leaguesPlayed': 'Serie A',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'KIMMICH',
                'playedAt': 'RB Leipzig,Bayern Munich',
                'managedBy': 'Pep Guardiola,Hansi Flick,Thomas Tuchel',
                'playedWith': 'LEWANDOWSKI,NEUER,MULLER',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Champions League,Bundesliga',
                'leaguesPlayed': 'Bundesliga',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'MULLER',
                'playedAt': 'Bayern Munich',
                'managedBy': 'Pep Guardiola,Hansi Flick',
                'playedWith': 'LEWANDOWSKI,NEUER,KIMMICH',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,Bundesliga',
                'leaguesPlayed': 'Bundesliga',
                'position': 'Atacante',
                'goals': 250,
            },
            {
                'name': 'NEUER',
                'playedAt': 'Schalke 04,Bayern Munich',
                'managedBy': 'Pep Guardiola,Hansi Flick',
                'playedWith': 'LEWANDOWSKI,MULLER,KIMMICH',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,Bundesliga',
                'leaguesPlayed': 'Bundesliga',
                'position': 'Goleiro',
                'goals': 0,
            },
            {
                'name': 'GORETZKA',
                'playedAt': 'Bochum,Schalke 04,Bayern Munich',
                'managedBy': 'Hansi Flick,Thomas Tuchel',
                'playedWith': 'LEWANDOWSKI,KIMMICH',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Champions League,Bundesliga',
                'leaguesPlayed': 'Bundesliga',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'SANÉ',
                'playedAt': 'Schalke 04,Manchester City,Bayern Munich',
                'managedBy': 'Pep Guardiola,Hansi Flick',
                'playedWith': 'DE BRUYNE,LEWANDOWSKI',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Premier League,Bundesliga',
                'leaguesPlayed': 'Bundesliga,Premier League',
                'position': 'Atacante',
                'goals': 150,
            },
            {
                'name': 'MUSIALA',
                'playedAt': 'Bayern Munich',
                'managedBy': 'Hansi Flick,Thomas Tuchel',
                'playedWith': 'LEWANDOWSKI,KIMMICH',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Bundesliga',
                'leaguesPlayed': 'Bundesliga',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'ALEXANDER-ARNOLD',
                'playedAt': 'Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,MANE,ALISSON',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Lateral',
                'goals': 20,
            },
            {
                'name': 'ROBERTSON',
                'playedAt': 'Queen Park,Dundee United,Hull City,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,MANE,VAN DIJK',
                'nationality': 'Escócia',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Lateral',
                'goals': 10,
            },
            {
                'name': 'KONATE',
                'playedAt': 'Sochaux,RB Leipzig,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'VAN DIJK,ALISSON',
                'nationality': 'França',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Ligue 1,Bundesliga,Premier League',
                'position': 'Zagueiro',
                'goals': 5,
            },
            {
                'name': 'MAC ALLISTER',
                'playedAt': 'Argentinos Juniors,Brighton,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,ALISSON',
                'nationality': 'Argentina',
                'trophiesEarned': 'Copa do Mundo,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Meio-campo',
                'goals': 30,
            },
            {
                'name': 'SZOBOSZLAI',
                'playedAt': 'RB Salzburg,RB Leipzig,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH',
                'nationality': 'Hungria',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Bundesliga,Premier League',
                'position': 'Meio-campo',
                'goals': 40,
            },
            {
                'name': 'DIAZ',
                'playedAt': 'Barranquilla,Porto,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH',
                'nationality': 'Colômbia',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Primeira Liga,Premier League',
                'position': 'Atacante',
                'goals': 50,
            },
            {
                'name': 'JOTA',
                'playedAt': 'Pacos Ferreira,Porto,Wolves,Liverpool',
                'managedBy': 'Jurgen Klopp',
                'playedWith': 'M. SALAH,MANE',
                'nationality': 'Portugal',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Primeira Liga,Premier League',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'GUNDOGAN',
                'playedAt': 'Nurnberg,Borussia Dortmund,Manchester City,Barcelona',
                'managedBy': 'Pep Guardiola,Xavi',
                'playedWith': 'DE BRUYNE,HAALAND',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Bundesliga,Premier League,La Liga',
                'position': 'Meio-campo',
                'goals': 100,
            },
            {
                'name': 'BERNARDO SILVA',
                'playedAt': 'Benfica,Monaco,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'DE BRUYNE,HAALAND,FODEN',
                'nationality': 'Portugal',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Primeira Liga,Ligue 1,Premier League',
                'position': 'Meio-campo',
                'goals': 100,
            },
            {
                'name': 'WALKER',
                'playedAt': 'Sheffield United,Tottenham,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'DE BRUYNE,HAALAND',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Lateral',
                'goals': 10,
            },
            {
                'name': 'STONES',
                'playedAt': 'Barnsley,Everton,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'DE BRUYNE,HAALAND',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Zagueiro',
                'goals': 10,
            },
            {
                'name': 'DIAS',
                'playedAt': 'Benfica,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'DE BRUYNE,HAALAND,EDERSON',
                'nationality': 'Portugal',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Primeira Liga,Premier League',
                'position': 'Zagueiro',
                'goals': 5,
            },
            {
                'name': 'AKANJI',
                'playedAt': 'Basel,Borussia Dortmund,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'HAALAND,DE BRUYNE',
                'nationality': 'Suíça',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Bundesliga,Premier League',
                'position': 'Zagueiro',
                'goals': 5,
            },
            {
                'name': 'GREALISH',
                'playedAt': 'Notts County,Aston Villa,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'HAALAND,DE BRUYNE,FODEN',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Champions League,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Atacante',
                'goals': 50,
            },
            {
                'name': 'ALVAREZ',
                'playedAt': 'River Plate,Manchester City',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'HAALAND,DE BRUYNE',
                'nationality': 'Argentina',
                'trophiesEarned': 'Copa do Mundo,Champions League,Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Atacante',
                'goals': 80,
            },
            {
                'name': 'DONNARUMMA',
                'playedAt': 'AC Milan,PSG',
                'managedBy': 'Thomas Tuchel',
                'playedWith': 'MBAPPE,NEYMAR JR',
                'nationality': 'Itália',
                'trophiesEarned': 'Eurocopa,Ligue 1',
                'leaguesPlayed': 'Serie A,Ligue 1',
                'position': 'Goleiro',
                'goals': 0,
            },
            {
                'name': 'HAKIMI',
                'playedAt': 'Real Madrid,Borussia Dortmund,Inter Milan,PSG',
                'managedBy': 'Thomas Tuchel,Antonio Conte',
                'playedWith': 'MBAPPE,NEYMAR JR',
                'nationality': 'Marrocos',
                'trophiesEarned': 'Ligue 1',
                'leaguesPlayed': 'Bundesliga,Serie A,Ligue 1',
                'position': 'Lateral',
                'goals': 20,
            },
            {
                'name': 'VERRATTI',
                'playedAt': 'Pescara,PSG,Al Arabi',
                'managedBy': 'Thomas Tuchel,Unai Emery',
                'playedWith': 'NEYMAR JR,MBAPPE,IBRAHIMOVIC',
                'nationality': 'Itália',
                'trophiesEarned': 'Eurocopa,Ligue 1',
                'leaguesPlayed': 'Serie A,Ligue 1',
                'position': 'Meio-campo',
                'goals': 20,
            },
            {
                'name': 'IBRAHIMOVIC',
                'playedAt': 'Malmo,Ajax,Juventus,Inter Milan,Barcelona,AC Milan,PSG,Manchester United,LA Galaxy,AC Milan',
                'managedBy': 'Pep Guardiola,Unai Emery',
                'playedWith': 'MESSI,NEYMAR JR,VERRATTI',
                'nationality': 'Suécia',
                'trophiesEarned': 'Champions League,La Liga,Ligue 1,Serie A',
                'leaguesPlayed': 'Eredivisie,Serie A,La Liga,Ligue 1,Premier League,MLS',
                'position': 'Atacante',
                'goals': 500,
            },
            {
                'name': 'CAVANI',
                'playedAt': 'Danubio,Palermo,Napoli,PSG,Manchester United,Valencia,Boca Juniors',
                'managedBy': 'Unai Emery,Ole Gunnar Solskjaer',
                'playedWith': 'NEYMAR JR,MBAPPE',
                'nationality': 'Uruguai',
                'trophiesEarned': 'Copa América,Ligue 1',
                'leaguesPlayed': 'Serie A,Ligue 1,Premier League,La Liga',
                'position': 'Atacante',
                'goals': 400,
            },
            {
                'name': 'DI MARIA',
                'playedAt': 'Rosario Central,Benfica,Real Madrid,Manchester United,PSG,Juventus,Benfica',
                'managedBy': 'Carlo Ancelotti,Unai Emery',
                'playedWith': 'RONALDO,MESSI,MBAPPE',
                'nationality': 'Argentina',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga,Ligue 1',
                'leaguesPlayed': 'Primeira Liga,La Liga,Premier League,Ligue 1,Serie A',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'MOUNT',
                'playedAt': 'Vitesse,Derby County,Chelsea,Manchester United',
                'managedBy': 'Frank Lampard,Thomas Tuchel,Erik ten Hag',
                'playedWith': 'HAVERTZ',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Champions League',
                'leaguesPlayed': 'Premier League',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'HAVERTZ',
                'playedAt': 'Bayer Leverkusen,Chelsea,Arsenal',
                'managedBy': 'Thomas Tuchel,Mikel Arteta',
                'playedWith': 'MOUNT',
                'nationality': 'Alemanha',
                'trophiesEarned': 'Champions League',
                'leaguesPlayed': 'Bundesliga,Premier League',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'JAMES',
                'playedAt': 'Banfield,Porto,Monaco,Real Madrid,Bayern Munich,Everton,Al Rayyan,Sao Paulo',
                'managedBy': 'Carlo Ancelotti,Zidane',
                'playedWith': 'RONALDO,BENZEMA',
                'nationality': 'Colômbia',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'Primeira Liga,Ligue 1,La Liga,Bundesliga,Premier League',
                'position': 'Meio-campo',
                'goals': 100,
            },
            {
                'name': 'POGBA',
                'playedAt': 'Le Havre,Manchester United,Juventus,Manchester United,Juventus',
                'managedBy': 'Massimiliano Allegri,Jose Mourinho',
                'playedWith': 'RONALDO,CHIESA',
                'nationality': 'França',
                'trophiesEarned': 'Copa do Mundo,Serie A',
                'leaguesPlayed': 'Premier League,Serie A',
                'position': 'Meio-campo',
                'goals': 80,
            },
            {
                'name': 'KANTE',
                'playedAt': 'Boulogne,Caen,Leicester City,Chelsea,Al Ittihad',
                'managedBy': 'Claudio Ranieri,Antonio Conte,Thomas Tuchel',
                'playedWith': 'HAZARD',
                'nationality': 'França',
                'trophiesEarned': 'Copa do Mundo,Champions League,Premier League',
                'leaguesPlayed': 'Ligue 1,Premier League',
                'position': 'Meio-campo',
                'goals': 20,
            },
            {
                'name': 'HAZARD',
                'playedAt': 'Lille,Chelsea,Real Madrid',
                'managedBy': 'Antonio Conte,Zidane',
                'playedWith': 'KANTE,COURTOIS',
                'nationality': 'Bélgica',
                'trophiesEarned': 'Premier League,La Liga',
                'leaguesPlayed': 'Ligue 1,Premier League,La Liga',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'STERLING',
                'playedAt': 'QPR,Liverpool,Manchester City,Chelsea',
                'managedBy': 'Pep Guardiola',
                'playedWith': 'DE BRUYNE,HAALAND',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Atacante',
                'goals': 200,
            },
            {
                'name': 'PULISIC',
                'playedAt': 'Borussia Dortmund,Chelsea,AC Milan',
                'managedBy': 'Thomas Tuchel',
                'playedWith': 'HAVERTZ',
                'nationality': 'Estados Unidos',
                'trophiesEarned': 'Champions League',
                'leaguesPlayed': 'Bundesliga,Premier League,Serie A',
                'position': 'Atacante',
                'goals': 80,
            },
            {
                'name': 'ZINCHENKO',
                'playedAt': 'Ufa,Manchester City,Arsenal',
                'managedBy': 'Pep Guardiola,Mikel Arteta',
                'playedWith': 'DE BRUYNE,HAALAND',
                'nationality': 'Ucrânia',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Lateral',
                'goals': 10,
            },
            {
                'name': 'RICE',
                'playedAt': 'West Ham,Arsenal',
                'managedBy': 'Mikel Arteta',
                'playedWith': 'SAKA,MARTINELLI',
                'nationality': 'Inglaterra',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Premier League',
                'position': 'Meio-campo',
                'goals': 20,
            },
            {
                'name': 'ODEgaard',
                'playedAt': 'Stromsgodset,Heerenveen,Vitesse,Real Madrid,Real Sociedad,Arsenal',
                'managedBy': 'Mikel Arteta',
                'playedWith': 'SAKA,MARTINELLI',
                'nationality': 'Noruega',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Eredivisie,La Liga,Premier League',
                'position': 'Meio-campo',
                'goals': 50,
            },
            {
                'name': 'SALIBA',
                'playedAt': 'Saint-Etienne,Nice,Marseille,Arsenal',
                'managedBy': 'Mikel Arteta',
                'playedWith': 'SAKA,MARTINELLI',
                'nationality': 'França',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Ligue 1,Premier League',
                'position': 'Zagueiro',
                'goals': 5,
            },
            {
                'name': 'GABRIEL',
                'playedAt': 'Avai,Lille,Arsenal',
                'managedBy': 'Mikel Arteta',
                'playedWith': 'SAKA,MARTINELLI',
                'nationality': 'Brasil',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'Brasileirão,Ligue 1,Premier League',
                'position': 'Zagueiro',
                'goals': 10,
            },
            {
                'name': 'PARTEY',
                'playedAt': 'Atletico Madrid,Arsenal',
                'managedBy': 'Diego Simeone,Mikel Arteta',
                'playedWith': 'GRIEZMANN,SAKA',
                'nationality': 'Gana',
                'trophiesEarned': 'Premier League',
                'leaguesPlayed': 'La Liga,Premier League',
                'position': 'Meio-campo',
                'goals': 20,
            },
            {
                'name': 'JOÃO FELIX',
                'playedAt': 'Benfica,Atletico Madrid,Chelsea,Barcelona',
                'managedBy': 'Diego Simeone,Xavi',
                'playedWith': 'GRIEZMANN,LEWANDOWSKI',
                'nationality': 'Portugal',
                'trophiesEarned': 'La Liga',
                'leaguesPlayed': 'Primeira Liga,La Liga,Premier League',
                'position': 'Atacante',
                'goals': 100,
            },
            {
                'name': 'BUSQUETS',
                'playedAt': 'Barcelona,Inter Miami',
                'managedBy': 'Pep Guardiola,Luis Enrique,Xavi',
                'playedWith': 'MESSI,XAVI,INIESTA',
                'nationality': 'Espanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga',
                'leaguesPlayed': 'La Liga,MLS',
                'position': 'Meio-campo',
                'goals': 20,
            },
            {
                'name': 'PIQUE',
                'playedAt': 'Manchester United,Zaragoza,Barcelona',
                'managedBy': 'Pep Guardiola,Luis Enrique',
                'playedWith': 'MESSI,XAVI,INIESTA',
                'nationality': 'Espanha',
                'trophiesEarned': 'Copa do Mundo,Champions League,La Liga',
                'leaguesPlayed': 'Premier League,La Liga',
                'position': 'Zagueiro',
                'goals': 50,
            },
            {
                'name': 'JORDI ALBA',
                'playedAt': 'Valencia,Barcelona,Inter Miami',
                'managedBy': 'Luis Enrique,Xavi',
                'playedWith': 'MESSI,INIESTA',
                'nationality': 'Espanha',
                'trophiesEarned': 'Champions League,La Liga',
                'leaguesPlayed': 'La Liga,MLS',
                'position': 'Lateral',
                'goals': 30,
            },
            {
                'name': 'COSTA',
                'playedAt': 'Penafiel,Porto,Atletico Madrid,Chelsea,Atletico Madrid',
                'managedBy': 'Diego Simeone,Antonio Conte',
                'playedWith': 'GRIEZMANN',
                'nationality': 'Espanha',
                'trophiesEarned': 'La Liga,Premier League',
                'leaguesPlayed': 'Primeira Liga,La Liga,Premier League',
                'position': 'Atacante',
                'goals': 200,
            },
        ]
        
        # Insere os jogadores no banco
        added_count = 0
        skipped_count = 0
        
        for player_data in players_data:
            # Verifica se o jogador já existe (por nome)
            existing_player = Player.query.filter_by(name=player_data['name']).first()
            
            if existing_player:
                print(f"⏭️  Jogador {player_data['name']} já existe. Pulando...")
                skipped_count += 1
                continue
            
            # Cria novo jogador
            player = Player(**player_data)
            db.session.add(player)
            added_count += 1
            print(f"✅ Adicionado: {player_data['name']}")
        
        # Salva as alterações
        db.session.commit()
        
        print("\n" + "="*50)
        print(f"✅ Seed concluído!")
        print(f"   📊 Jogadores adicionados: {added_count}")
        print(f"   ⏭️  Jogadores pulados: {skipped_count}")
        print(f"   📈 Total no banco: {Player.query.count()}")
        print("="*50)


if __name__ == '__main__':
    seed_players()

